server:
  port: 8080


#data-source
spring:
  datasource:
    url: jdbc:mysql://47.97.205.190:3306/finding-pet?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: gx123456
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.bluesgao.findingpet.entity
  global-config:
    db-config:
      table-underline: true

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
